baseURL = "www.yopen.org"
languageCode = "en-us"
title = "Yearn Open"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "yearn finance"

  [params.homepage_meta_tags]
    meta_description = "Yearn Open aggregates and produces reports for the entire Yearn Ecosystem"
    meta_og_title = "Yearn Open"
    meta_og_type = "website"
    meta_og_url = "https://yopen.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Yearn Open aggregates and produces reports for the entire Yearn Ecosystem"
    meta_twitter_card = "summary"
    meta_twitter_site = "@yearnfinance"
    meta_twitter_creator = "@yearnfinance"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Yearn Open <a class="yearnfinance" href="https://www.yearn.finance">www.yearn.finance</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Reports"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Open Source"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "GitHub"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Request Reports"
    url = "/contact/"
      weight = 2
